# run nginx in foreground
daemon off;
pid /run/nginx.pid;
user root;

# Set number of worker processes automatically based on number of CPU cores.
worker_processes auto;

# Enables the use of JIT for regular expressions to speed-up their processing.
pcre_jit on;

error_log {{.LogsPath}}/fallback_error.log warn;

# Includes files with directives to load dynamic modules.
include {{.NginxPath}}/modules/*.conf;

# Custom
include {{.ConfigPath}}/custom/root_top[.]conf;

events {
	include {{.ConfigPath}}/custom/events[.]conf;
}
http {
	include                       {{.NginxPath}}/mime.types;
	default_type                  application/octet-stream;
	sendfile                      on;
	server_tokens                 off;
	tcp_nopush                    on;
	tcp_nodelay                   on;
	client_body_temp_path         /tmp/nginx/body 1 2;
	keepalive_timeout             90s;
	proxy_connect_timeout         90s;
	proxy_send_timeout            90s;
	proxy_read_timeout            90s;
	ssl_prefer_server_ciphers     on;
	gzip                          on;
	proxy_ignore_client_abort     off;
	client_max_body_size          2000m;
	server_names_hash_bucket_size 1024;
	proxy_http_version            1.1;
	proxy_set_header              X-Forwarded-Scheme $scheme;
	proxy_set_header              X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header              Accept-Encoding "";
	#proxy_cache                   off;
	#proxy_cache_path              /var/lib/nginx/cache/public  levels=1:2 keys_zone=public-cache:30m max_size=192m;
	#proxy_cache_path              /var/lib/nginx/cache/private levels=1:2 keys_zone=private-cache:5m max_size=1024m;	

	error_page                      403 /error/404/index.html;
	error_page                      404 /error/404/index.html;
	error_page                      410 /error/410/index.html;
	error_page                      500 501 502 503 504 505 /error/50x/index.html;


	# Log format and fallback log file
	include {{.NginxPath}}/conf.d/include/log.conf;
	# Dynamically generated resolvers file
	include {{.NginxPath}}/conf.d/include/resolvers.conf;

	# Default upstream scheme
	map $host $forward_scheme {
		default http;
	}

	# Real IP Determination

	# Local subnets:
	#set_real_ip_from 10.0.0.0/8;
	#set_real_ip_from 172.16.0.0/12; # Includes Docker subnet
	#set_real_ip_from 192.168.0.0/16;
	# NPM generated CDN ip ranges:
	#include conf.d/include/ip_ranges.conf;
	# always put the following 2 lines after ip subnets:
	#real_ip_header X-Real-IP;
	#real_ip_recursive on;

	# Custom
	include {{.ConfigPath}}/custom/http_top[.]conf;

	# Files generated by ProxyManager
	include {{.NginxPath}}/conf.d/*.conf;


	# Main File
	include {{.ConfigPath}}/main.conf;
	# Custom
	include {{.ConfigPath}}/custom/http[.]conf;	
}
{{ if .EnableStreams}}
stream {
	# Files generated by NPM
	include {{.ConfigPath}}/stream/*.conf;

	# Custom
	include {{.ConfigPath}}/custom/stream[.]conf;
}
{{end}}
# Custom
include {{.ConfigPath}}/custom/root[.]conf;
